import { useEffect,useState } from "react";
import { useNavigate,useSearchParams } from "react-router-dom";
import { listProfessionalResults,listResultValidations,validateProfessionalResult } from "../services/professionalValidation";
import "../styles/dashboard-master.css";

export default function CommissionProfessionalValidation(){
  const navigate=useNavigate(),[params]=useSearchParams();
  const projectId=params.get("projeto")||"",participantId=params.get("participante")||"";
  const [results,setResults]=useState([]),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[decision,setDecision]=useState("aprovado"),[opinion,setOpinion]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  async function load(){if(!projectId)return;try{const rows=await listProfessionalResults(projectId);setResults(participantId?(rows||[]).filter(x=>String(x.participante_id||x.atleta_participante_id||"")===participantId):(rows||[]));}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[projectId,participantId]);
  async function choose(item){setSelected(item);setMessage("");try{setHistory(await listResultValidations(item.id));}catch(e){setError(e.message)}}
  async function submit(e){e.preventDefault();if(!selected)return;setSaving(true);setError("");try{await validateProfessionalResult(selected.id,{decisao:decision,parecer_tecnico:opinion,papel_profissional:"comissao_tecnica",visivel_atleta:false,visivel_comissao:true,visivel_instituicao:false,substitui_resultado_id:null,motivo_substituicao:null});setMessage("Decisão registrada no histórico.");setOpinion("");setHistory(await listResultValidations(selected.id));await load();}catch(x){setError(x.message)}finally{setSaving(false)}}
  return <main className="dashboard-master"><div className="dashboard-overlay master-page"><header className="dashboard-header master-header"><div><span className="master-eyebrow">Comissão técnica</span><h1>Decisão sobre evidências</h1><p>Valide somente resultados pertinentes ao atleta sob sua responsabilidade.</p></div><button className="master-button secondary" onClick={()=>navigate("/dashboard-comissao")}>Voltar</button></header>{error&&<div className="master-error">{error}</div>}{message&&<div className="master-success">{message}</div>}<section className="master-content-grid"><article className="master-panel"><h2>Fila de decisão</h2>{!projectId?<p>Projeto não informado.</p>:results.length===0?<p>Nenhum resultado aguardando decisão.</p>:<ul className="master-activity-list">{results.map(x=><li key={x.id}><button className="master-link-button" onClick={()=>choose(x)}><strong>{x.tipo||"Resultado analítico"}</strong><span>{x.status||"preliminar"}</span></button></li>)}</ul>}</article><article className="master-panel">{!selected?<p>Selecione um resultado.</p>:<form onSubmit={submit} className="master-form-grid"><h2>{selected.tipo||"Resultado"}</h2><p>{selected.explicacao||selected.parecer_tecnico||"Sem explicação registrada."}</p><label>Decisão<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="aprovado">Aprovar</option><option value="rejeitado">Rejeitar</option></select></label><label className="full-width">Parecer técnico<textarea rows="5" minLength="10" required value={opinion} onChange={e=>setOpinion(e.target.value)}/></label><button className="master-button" disabled={saving}>{saving?"Registrando…":"Registrar decisão"}</button></form>}</article></section>{history.length>0&&<details className="master-panel"><summary>Histórico da decisão</summary><ul className="master-activity-list">{history.map(x=><li key={x.id}><strong>{x.decisao}</strong><span>{x.parecer_tecnico}</span></li>)}</ul></details>}</div></main>;
}
