import { useEffect, useMemo, useState } from "react";
import { supabase } from "../supabaseClient";
import "../styles/dashboard-comissao.css";

function status(row) { if (!row.ultimaResposta) return { label:"Sem registro recente", level:2 }; const hours=(Date.now()-new Date(row.ultimaResposta).getTime())/3600000; if (hours>48 || Number(row.adesao7d)<50) return {label:"Precisa de atenção",level:2}; if (hours>24 || Number(row.adesao7d)<80) return {label:"Acompanhar",level:1}; return {label:"Sem pendência imediata",level:0}; }
export default function DashboardComissao(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState(null),[history,setHistory]=useState([]);
 async function load(){setLoading(true);setError("");const {data:s}=await supabase.auth.getSession();if(!s?.session){window.location.href="/";return;}const {data:links,error:e}=await supabase.from("agp_atletas_projeto").select("id,projeto_id,atleta_id,status").eq("status","ativo");if(e){setError("Não foi possível carregar seus atletas.");setLoading(false);return;}const ids=[...new Set((links||[]).map(x=>x.atleta_id))];if(!ids.length){setRows([]);setLoading(false);return;}const [p,a]=await Promise.all([supabase.from("perfis_atletas").select("id,nome,categoria,nivel").in("id",ids),supabase.from("agp_adesao_questionario_diario").select("projeto_id,atleta_id,respostas_7d,adesao_7d_percentual,ultima_resposta").in("atleta_id",ids)]);if(p.error||a.error){setError("Não foi possível carregar o acompanhamento agora.");setLoading(false);return;}const pm=Object.fromEntries((p.data||[]).map(x=>[x.id,x])),am=Object.fromEntries((a.data||[]).map(x=>[`${x.projeto_id}:${x.atleta_id}`,x]));setRows((links||[]).map(x=>{const q=am[`${x.projeto_id}:${x.atleta_id}`]||{};return{...x,athlete:pm[x.atleta_id],respostas7d:Number(q.respostas_7d||0),adesao7d:Number(q.adesao_7d_percentual||0),ultimaResposta:q.ultima_resposta||null};}));setLoading(false);}
 async function open(row){setSelected(row);setHistory([]);const {data,error:e}=await supabase.from("agp_coletas").select("id,data_hora_coleta,status,completude,confiabilidade,dados").eq("atleta_id",row.atleta_id).eq("projeto_id",row.projeto_id).order("data_hora_coleta",{ascending:false}).limit(14);if(e)setError("Não foi possível abrir o histórico deste atleta.");else setHistory(data||[]);}
 useEffect(()=>{load();},[]);const ordered=useMemo(()=>[...rows].sort((a,b)=>status(b).level-status(a).level),[rows]);const attention=ordered.filter(x=>status(x).level>0);
 if(loading)return <div className="dashboard-loading">Preparando seu acompanhamento...</div>;
 return <main className="dashboard-comissao"><div className="dashboard-overlay"><header className="dashboard-header"><div><span>AGP · Acompanhamento profissional</span><h1>Quem precisa da sua atenção agora?</h1><p>O AGP organiza seus atletas pela necessidade de acompanhamento.</p></div><button onClick={load}>Atualizar</button></header>{error&&<div className="master-error" role="alert">{error}</div>}
 <section className="dashboard-section"><h2>{attention.length?`${attention.length} atleta${attention.length>1?"s":""} para acompanhar`:"Nenhuma pendência imediata"}</h2>{ordered.length===0?<div className="dashboard-loading">Nenhum atleta ativo está vinculado a este acesso.</div>:<div className="athlete-grid">{ordered.map(row=>{const s=status(row);return <article key={row.id} className={`athlete-card ${s.level===2?"critical":s.level===1?"warning":"ok"}`}><h3>{row.athlete?.nome||"Atleta"}</h3><p>{row.athlete?.categoria||row.athlete?.nivel||""}</p><strong>{s.label}</strong><button onClick={()=>open(row)}>Abrir acompanhamento</button></article>})}</div>}</section>
 {selected&&<section className="dashboard-section"><h2>{selected.athlete?.nome}</h2>{history.length===0?<p>Ainda não há evidências disponíveis para este atleta.</p>:<div className="alert-list">{history.map(item=><article key={item.id} className="athlete-card"><strong>{new Date(item.data_hora_coleta).toLocaleString("pt-BR")}</strong><span>Registro {item.status}</span><details><summary>Ver evidência</summary><pre>{JSON.stringify(item.dados,null,2)}</pre></details></article>)}</div>}</section>}
 <details className="dashboard-section"><summary>Ver indicadores de acompanhamento</summary><div className="athlete-grid">{ordered.map(row=><article key={`metric-${row.id}`} className="athlete-card"><h3>{row.athlete?.nome||"Atleta"}</h3><span>{row.adesao7d.toFixed(0)}% de adesão em 7 dias</span><span>{row.respostas7d} registros válidos</span></article>)}</div></details>
 </div></main>;
}
