import { useEffect,useMemo,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { supabase } from "../supabaseClient";
import { listProjectParticipants } from "../services/participantOnboarding";
import { formatEligibilityPending,listProjectEligibility } from "../services/eligibilityManagement";
import AgpEvidenceReadiness from "../components/AgpEvidenceReadiness";
import "../styles/dashboard-master.css";
export default function HomologationEnvironment(){
 const {slug}=useParams(),navigate=useNavigate();
 const [institution,setInstitution]=useState(null),[project,setProject]=useState(null),[profiles,setProfiles]=useState([]),[links,setLinks]=useState([]),[participants,setParticipants]=useState([]),[eligibility,setEligibility]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const i=await supabase.from("agp_instituicoes").select("*").eq("slug",slug).maybeSingle();if(i.error||!i.data){setError("Ambiente de homologação não encontrado.");setLoading(false);return;}setInstitution(i.data);const [p,l]=await Promise.all([supabase.from("agp_projetos_validacao").select("*").eq("instituicao_id",i.data.id).maybeSingle(),supabase.from("perfis_atletas").select("*").order("nome")]);if(p.error||l.error)setError((p.error||l.error).message);setProject(p.data||null);setProfiles(l.data||[]);if(p.data){const h=await supabase.from("agp_atletas_projeto").select("*").eq("projeto_id",p.data.id).order("created_at");setLinks(h.data||[]);try{const [a,e]=await Promise.all([listProjectParticipants(p.data.id),listProjectEligibility(p.data.id)]);setParticipants(a||[]);setEligibility(e||[]);}catch(x){setError(x.message);}}setLoading(false);}
 useEffect(()=>{load();},[slug]);
 const profileById=useMemo(()=>Object.fromEntries(profiles.map(x=>[x.id,x])),[profiles]);
 const byParticipant=useMemo(()=>Object.fromEntries(eligibility.map(x=>[x.participante_id,x])),[eligibility]);
 const technicians=participants.filter(x=>["tecnico","treinador"].includes(x.funcao_no_projeto)),athletes=participants.filter(x=>x.funcao_no_projeto==="atleta");
 const collect=eligibility.filter(x=>x.apto_coleta).length,analyse=eligibility.filter(x=>x.apto_analise).length;
 const next=technicians.length===0?{title:"Vincular técnico",text:"A homologação precisa de responsabilidade profissional antes da coleta.",action:"Abrir Central de Participantes",go:()=>navigate("/master/participantes")} : athletes.length===0?{title:"Cadastrar atleta de homologação",text:"Crie o participante controlado que percorrerá o ciclo completo.",action:"Abrir Central de Participantes",go:()=>navigate("/master/participantes")} : collect<athletes.length?{title:"Resolver elegibilidade para coleta",text:"Há atleta com pendência de consentimento, linha de base, técnico ou instrumento.",action:"Ver participantes",go:()=>navigate("/master/participantes")} : {title:"Executar coleta controlada",text:"Identidade e elegibilidade estão prontas. Avance para a evidência sem simular conclusão científica.",action:"Abrir coleta",go:()=>navigate(`/master/coletas?projeto=${project?.id}`)};
 if(loading)return <main className="dashboard-master"><div className="dashboard-loading">Carregando homologação...</div></main>;
 return <main className="dashboard-master"><div className="dashboard-overlay master-page">
 <header className="dashboard-header master-header"><div><span className="master-eyebrow">Homologação integral</span><h1>{institution?.nome||"Homologação"}</h1><p>{project?.objetivo}</p></div><button className="master-button secondary" onClick={()=>navigate("/master/homologacao")}>Voltar</button></header>
 {error&&<div className="master-error" role="alert">{error}</div>}
 <section className="decision-hero"><div><span className="master-eyebrow">Próxima ação</span><h2>{next.title}</h2><p>{next.text}</p><button className="master-button" onClick={next.go}>{next.action}</button></div><div className="decision-score"><strong>{analyse}/{athletes.length}</strong><span>aptos para análise</span></div></section>
 <section className="master-content-grid"><article className="master-panel"><span className="master-eyebrow">Coleta</span><h2>{collect}/{athletes.length}</h2><p>Atletas liberados pela elegibilidade oficial.</p></article><article className="master-panel"><span className="master-eyebrow">Equipe</span><h2>{technicians.length}</h2><p>Técnicos responsáveis vinculados ao projeto.</p></article></section>
 {project&&<AgpEvidenceReadiness projectId={project.id} athleteLinks={links} profileById={profileById}/>} 
 <details className="master-panel"><summary>Ver participantes e pendências</summary>{athletes.length===0?<div className="master-empty">Nenhum atleta controlado vinculado.</div>:<ul className="master-activity-list">{athletes.map(x=>{const s=byParticipant[x.participante_id]||{apto_coleta:false,apto_analise:false,pendencias:["elegibilidade_indisponivel"]};const pending=formatEligibilityPending(s.pendencias||[]);return <li key={x.participante_id}><div><strong>{x.nome}</strong><span>Coleta: {s.apto_coleta?"liberada":"bloqueada"} · Análise: {s.apto_analise?"liberada":"bloqueada"}</span>{pending.length>0&&<small>{pending.join(" · ")}</small>}</div><b>{s.apto_analise?"Apto":s.apto_coleta?"Só coleta":"Bloqueado"}</b></li>})}</ul>}</details>
 <details className="master-panel"><summary>Ver governança e compatibilidade</summary><p>Status do projeto: <strong>{project?.status||"indisponível"}</strong>. Vínculos históricos preservados somente para compatibilidade: <strong>{links.length}</strong>.</p></details>
 </div></main>;
}