import {useEffect,useMemo,useState} from "react";
import {useLocation,useNavigate} from "react-router-dom";
import {listInstitutions} from "../services/institutionManagement";
import {createProject,listProjects} from "../services/projectManagement";
import InstitutionBrand from "../components/InstitutionBrand";
import "../styles/dashboard-master.css";
import "../styles/institution-brand.css";

export default function MasterProjects(){
 const navigate=useNavigate(),location=useLocation();
 const contextual=new URLSearchParams(location.search).get("context")==="natacao";
 const [institutions,setInstitutions]=useState([]),[projects,setProjects]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const[i,p]=await Promise.all([listInstitutions(),listProjects()]);setInstitutions(i||[]);setProjects(p||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const n1=useMemo(()=>institutions.find(x=>x.slug==="n1-academia")||institutions.find(x=>x.status==="ativo")||null,[institutions]);
 const swimming=useMemo(()=>projects.find(x=>x.instituicao_id===n1?.id&&/nata[cç][aã]o/i.test(x.nome||""))||null,[projects,n1]);
 async function activate(){if(!n1)return;setSaving(true);setError("");try{await createProject({instituicao_id:n1.id,nome:"N1 Academia · Natação",objetivo:"Operar e validar o ciclo longitudinal do AGP na modalidade Natação, integrando contexto esportivo, evidências, validação profissional, inteligência, intervenção, resposta e histórico do atleta.",metodologia:null,diretrizes:null,localidade:n1.localidade||null,data_inicio:null,data_fim:null,status:"preparacao",versao_motor:"agp-core-v2.1-traceable"});await load();navigate("/dashboard-master",{replace:true})}catch(e){setError(e.message)}finally{setSaving(false)}}
 if(contextual)return <main className="dashboard-master"><div className="dashboard-overlay master-page"><header className="dashboard-header master-header"><div><span className="master-eyebrow">Ativação esportiva</span><h1>N1 Academia · Natação</h1><p>O AGP já conhece instituição, modalidade, localidade e motor. O Master apenas confirma a ativação do contexto esportivo.</p></div><button className="master-button secondary" onClick={()=>navigate("/dashboard-master")}>Voltar</button></header>{n1&&<div className="institution-brand-preview"><InstitutionBrand institution={n1}/></div>}{error&&<div className="master-feedback error">{error}</div>}<section className="master-now-card"><span className="master-eyebrow">Contexto que será criado</span><h2>Natação</h2><p><strong>Instituição:</strong> {n1?.nome_exibicao||n1?.nome||"N1 Academia"}<br/><strong>Localidade:</strong> {n1?.localidade||"Ribeirão Preto/SP"}<br/><strong>Estado inicial:</strong> Preparação para homologação real<br/><strong>Motor:</strong> AGP Core rastreável</p>{loading?<button className="master-button master-primary-action" disabled>Carregando...</button>:swimming?<><div className="master-feedback success">A modalidade Natação já está ativa.</div><button className="master-button master-primary-action" onClick={()=>navigate("/dashboard-master")}>Voltar ao Centro Operacional</button></>:<button className="master-button master-primary-action" disabled={saving||!n1} onClick={activate}>{saving?"Ativando...":"Ativar Natação na N1"}</button>}</section></div></main>;
 return <main className="dashboard-master"><div className="dashboard-overlay master-page"><header className="dashboard-header master-header"><div><span className="master-eyebrow">Projetos esportivos</span><h1>Contextos ativos</h1><p>Use o Centro Operacional para iniciar novas modalidades. Esta área registra os contextos já existentes.</p></div><button className="master-button secondary" onClick={()=>navigate("/dashboard-master")}>Voltar</button></header>{error&&<div className="master-feedback error">{error}</div>}<section className="master-panel"><h2>Projetos cadastrados</h2>{loading?<p>Carregando...</p>:projects.length===0?<p>Nenhum projeto cadastrado.</p>:projects.map(p=><article className="master-list-row" key={p.id}><div><strong>{p.nome}</strong><span>{p.instituicao?.nome||"Instituição"} · {p.status}</span><small>{p.objetivo}</small></div></article>)}</section></div></main>;
}
