import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { createIntervention, createInterventionResponse, createProfessionalAssessment, getDecisionCycle } from "../services/multidisciplinaryDecision";
import "../styles/dashboard-master.css";
import "../styles/athlete-decision-cycle.css";
const DOMAINS=[["fisico","Físico"],["fisiologico","Fisiológico"],["biologico","Biológico"],["tecnico","Técnico"],["mental","Mental"],["psicologico","Psicológico"],["medico","Médico"],["recuperacao","Recuperação"],["contextual","Contextual"],["crescimento","Crescimento"],["maturacao","Maturação"],["nutricional","Nutricional"]];
const lines=v=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean);
function metrics(v){const out={};lines(v).forEach(line=>{const i=line.indexOf(":");if(i<0)return;const k=line.slice(0,i).trim(),raw=line.slice(i+1).trim(),n=Number(raw.replace(",","."));out[k]=raw!==""&&Number.isFinite(n)?n:raw;});return out;}
export default function MasterAthleteDecisionCycle(){
 const {participantId}=useParams(),navigate=useNavigate();
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [assessment,setAssessment]=useState({dominio:"fisico",papel:"preparador_fisico",instrumento:"",metricas:"",achados:"",restricoes:"",recomendacoes:"",confianca:""});
 const [intervention,setIntervention]=useState({dominio:"fisico",papel:"treinador",descricao:"",justificativa:"",resultado:""});
 const [response,setResponse]=useState({intervencao:"",papel:"treinador",antes:"",depois:"",classificacao:"inconclusiva",confianca:"",conclusao:"",proximo:""});
 async function load(){setLoading(true);setError("");try{setData(await getDecisionCycle(participantId));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[participantId]);
 const summary=data?.sintese||{},active=useMemo(()=>(data?.intervencoes||[]).filter(x=>["proposta","aprovada","em_execucao"].includes(x.status)),[data]);
 const evidence=useMemo(()=>{const a=data?.avaliacoes_profissionais?.[0];if(a)return[{tipo:"avaliacao_profissional",id:a.id,dominio:a.dominio}];const r=(data?.resultados_analiticos||[]).find(x=>x.status==="validado");return r?[{tipo:"resultado_analitico",id:r.id,versao_motor:r.versao_motor}]:[];},[data]);
 const next=!evidence.length?"avaliar":active.length?"responder":"intervir";
 async function saveAssessment(e){e.preventDefault();setSaving(true);setError("");try{await createProfessionalAssessment(participantId,{dominio:assessment.dominio,papel_profissional:assessment.papel,instrumento_referencia:assessment.instrumento||null,metricas:metrics(assessment.metricas),achados:lines(assessment.achados),restricoes:lines(assessment.restricoes),recomendacoes:lines(assessment.recomendacoes),confianca:assessment.confianca===""?null:Number(assessment.confianca)});setMessage("Avaliação integrada ao histórico.");await load();}catch(x){setError(x.message);}finally{setSaving(false);}}
 async function saveIntervention(e){e.preventDefault();setSaving(true);setError("");try{if(!evidence.length)throw new Error("Registre ou valide uma evidência antes da intervenção.");await createIntervention(participantId,{dominio:intervention.dominio,papel_responsavel:intervention.papel,descricao:intervention.descricao,justificativa:intervention.justificativa,evidencia_origem:evidence,resultado_esperado:{objetivo:intervention.resultado},status:"proposta"});setMessage("Intervenção vinculada à evidência.");await load();}catch(x){setError(x.message);}finally{setSaving(false);}}
 async function saveResponse(e){e.preventDefault();setSaving(true);setError("");try{await createInterventionResponse(response.intervencao,{papel_avaliador:response.papel,metricas_antes:metrics(response.antes),metricas_depois:metrics(response.depois),classificacao_resposta:response.classificacao,confianca:response.confianca===""?null:Number(response.confianca),conclusao:response.conclusao,recomendacao_proximo_ciclo:response.proximo||null});setMessage("Resposta incorporada ao histórico e ao próximo ciclo.");await load();}catch(x){setError(x.message);}finally{setSaving(false);}}
 if(loading)return <main className="dashboard-master"><div className="dashboard-overlay master-page"><div className="master-empty">Consolidando decisão...</div></div></main>;
 return <main className="dashboard-master"><div className="dashboard-overlay master-page decision-cycle-page">
 <header className="dashboard-header master-header"><div><span className="master-eyebrow">Decisão multidisciplinar</span><h1>Qual é a próxima ação?</h1><p>O AGP conduz avaliação, intervenção e resposta no mesmo ciclo.</p></div><button className="master-button secondary" onClick={()=>navigate(`/master/atletas/${participantId}`)}>Voltar ao atleta</button></header>
 {message&&<div className="master-success">{message}</div>}{error&&<div className="master-error">{error}</div>}
 <section className="decision-hero"><div><span className="master-eyebrow">Agora</span><h2>{next==="avaliar"?"Registrar ou validar evidência":next==="intervir"?"Definir intervenção":"Medir resposta à intervenção"}</h2><p>{summary.proxima_acao||"Complete a etapa indicada para avançar o ciclo."}</p></div><div className="decision-score"><strong>{summary.cobertura_multidisciplinar_percentual??0}%</strong><span>contexto disponível</span></div></section>
 {next==="avaliar"&&<form className="decision-form" onSubmit={saveAssessment}><span className="master-eyebrow">Avaliar</span><h2>Avaliação profissional</h2><div className="decision-two"><label>Domínio<select value={assessment.dominio} onChange={e=>setAssessment({...assessment,dominio:e.target.value})}>{DOMAINS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Papel profissional<input value={assessment.papel} onChange={e=>setAssessment({...assessment,papel:e.target.value})} required/></label></div><label>Instrumento ou teste<input value={assessment.instrumento} onChange={e=>setAssessment({...assessment,instrumento:e.target.value})}/></label><label>Métricas<textarea rows="4" value={assessment.metricas} onChange={e=>setAssessment({...assessment,metricas:e.target.value})}/></label><label>Achados<textarea rows="3" value={assessment.achados} onChange={e=>setAssessment({...assessment,achados:e.target.value})}/></label><label>Restrições<textarea rows="3" value={assessment.restricoes} onChange={e=>setAssessment({...assessment,restricoes:e.target.value})}/></label><label>Recomendações<textarea rows="3" value={assessment.recomendacoes} onChange={e=>setAssessment({...assessment,recomendacoes:e.target.value})}/></label><button className="master-button" disabled={saving}>Registrar avaliação</button></form>}
 {next==="intervir"&&<form className="decision-form" onSubmit={saveIntervention}><span className="master-eyebrow">Intervir</span><h2>Intervenção</h2><div className="decision-two"><label>Domínio<select value={intervention.dominio} onChange={e=>setIntervention({...intervention,dominio:e.target.value})}>{DOMAINS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Responsável<input value={intervention.papel} onChange={e=>setIntervention({...intervention,papel:e.target.value})} required/></label></div><label>O que será feito<textarea rows="4" value={intervention.descricao} onChange={e=>setIntervention({...intervention,descricao:e.target.value})} required/></label><label>Por quê<textarea rows="4" value={intervention.justificativa} onChange={e=>setIntervention({...intervention,justificativa:e.target.value})} required/></label><label>Resultado esperado<textarea rows="3" value={intervention.resultado} onChange={e=>setIntervention({...intervention,resultado:e.target.value})} required/></label><button className="master-button" disabled={saving}>Registrar intervenção</button></form>}
 {next==="responder"&&<form className="decision-form" onSubmit={saveResponse}><span className="master-eyebrow">Medir resposta</span><h2>Efeito da intervenção</h2><label>Intervenção<select value={response.intervencao} onChange={e=>setResponse({...response,intervencao:e.target.value})} required><option value="">Selecionar</option>{active.map(x=><option key={x.id} value={x.id}>{x.dominio} · {x.descricao?.slice(0,60)}</option>)}</select></label><label>Avaliador<input value={response.papel} onChange={e=>setResponse({...response,papel:e.target.value})} required/></label><div className="decision-two"><label>Métricas antes<textarea rows="4" value={response.antes} onChange={e=>setResponse({...response,antes:e.target.value})}/></label><label>Métricas depois<textarea rows="4" value={response.depois} onChange={e=>setResponse({...response,depois:e.target.value})}/></label></div><div className="decision-two"><label>Resposta<select value={response.classificacao} onChange={e=>setResponse({...response,classificacao:e.target.value})}><option value="melhora">Melhora</option><option value="neutra">Neutra</option><option value="piora">Piora</option><option value="inconclusiva">Inconclusiva</option></select></label><label>Confiança (0–100)<input type="number" min="0" max="100" step="1" value={response.confianca} onChange={e=>setResponse({...response,confianca:e.target.value})}/></label></div><label>Conclusão<textarea rows="3" value={response.conclusao} onChange={e=>setResponse({...response,conclusao:e.target.value})} required/></label><label>Próximo ciclo<textarea rows="3" value={response.proximo} onChange={e=>setResponse({...response,proximo:e.target.value})}/></label><button className="master-button" disabled={saving}>Registrar resposta</button></form>}
 <details className="master-panel"><summary>Ver contexto completo do ciclo</summary><div className="decision-kpis"><article><strong>{data?.avaliacoes_profissionais?.length||0}</strong><span>Avaliações</span></article><article><strong>{summary.resultados_validados||0}</strong><span>Resultados validados</span></article><article><strong>{summary.intervencoes_ativas||0}</strong><span>Intervenções abertas</span></article><article><strong>{summary.respostas_intervencao||0}</strong><span>Respostas medidas</span></article></div></details>
 </div></main>;
}