import { useEffect,useMemo,useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../supabaseClient";
import "../styles/dashboard-master.css";

const STEPS=["N1 como instituição-base","Projeto N1 · Natação de homologação","Técnico e profissionais","Atleta","Contexto e elegibilidade","Coleta de evidência","Validação da evidência","Cruzamento analítico","Validação do resultado","Intervenção","Resposta à intervenção","Histórico longitudinal"];

export default function MasterHomologationN1(){
 const navigate=useNavigate();
 const [institution,setInstitution]=useState(null),[project,setProject]=useState(null),[participants,setParticipants]=useState([]),[accounts,setAccounts]=useState([]),[cycle,setCycle]=useState({collections:[],executions:[],results:[],validations:[],interventions:[],responses:[]}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{
  const i=await supabase.from("agp_instituicoes").select("*").ilike("nome","%N1%Academia%").eq("status","ativo").order("created_at",{ascending:false}).limit(1).maybeSingle(); if(i.error)throw i.error; setInstitution(i.data||null); if(!i.data){setProject(null);return;}
  const p=await supabase.from("agp_projetos_validacao").select("*").eq("instituicao_id",i.data.id).eq("status","homologacao").order("created_at",{ascending:false}).limit(1).maybeSingle(); if(p.error)throw p.error; setProject(p.data||null); if(!p.data){setParticipants([]);setAccounts([]);return;}
  const [pa,c,e,r,it,resp]=await Promise.all([supabase.from("agp_participantes_projeto").select("id,pessoa_id,funcao_no_projeto,status_onboarding,ativo").eq("projeto_id",p.data.id),supabase.from("agp_coletas").select("id,status,bloqueado_para_edicao,liberado_motor_em").eq("projeto_id",p.data.id),supabase.from("agp_execucoes_analiticas").select("id,status").eq("projeto_id",p.data.id),supabase.from("agp_resultados_analiticos").select("id,status").eq("projeto_id",p.data.id),supabase.from("agp_intervencoes").select("id,status").eq("projeto_id",p.data.id),supabase.from("agp_respostas_intervencao").select("id,classificacao_resposta").eq("projeto_id",p.data.id)]);
  const first=pa.error||c.error||e.error||r.error||it.error||resp.error; if(first)throw first; const participantRows=pa.data||[]; setParticipants(participantRows);
  const personIds=participantRows.map(x=>x.pessoa_id).filter(Boolean); let accountRows=[]; if(personIds.length){const a=await supabase.from("agp_contas_acesso").select("id,pessoa_id,email_acesso,status,auth_id").in("pessoa_id",personIds); if(a.error)throw a.error; accountRows=a.data||[];} setAccounts(accountRows);
  const ids=(r.data||[]).map(x=>x.id); let validations=[]; if(ids.length){const v=await supabase.from("agp_validacoes_profissionais").select("id").in("resultado_id",ids); if(v.error)throw v.error; validations=v.data||[];} setCycle({collections:c.data||[],executions:e.data||[],results:r.data||[],validations,interventions:it.data||[],responses:resp.data||[]});
 }catch(x){setError(x.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const professionals=participants.filter(x=>x.funcao_no_projeto!=="atleta"),athletes=participants.filter(x=>x.funcao_no_projeto==="atleta");
 const professionalAccessReady=professionals.some(p=>accounts.some(a=>a.pessoa_id===p.pessoa_id&&a.auth_id));
 const validatedEvidence=cycle.collections.filter(x=>x.status==="validada"&&x.bloqueado_para_edicao&&x.liberado_motor_em).length;
 const complete=cycle.responses.length>0;
 const progress=useMemo(()=>[Boolean(institution),Boolean(project),professionals.length>0&&professionalAccessReady,athletes.length>0,athletes.some(x=>["ativo","apto_para_coleta"].includes(x.status_onboarding)),cycle.collections.length>0,validatedEvidence>0,cycle.executions.some(x=>x.status==="concluida"),cycle.validations.length>0,cycle.interventions.length>0,cycle.responses.length>0,complete],[institution,project,professionals.length,professionalAccessReady,athletes.length,cycle,validatedEvidence,complete]);
 const next=!institution?{title:"N1 não localizada",text:"A instituição-base precisa existir.",label:"Abrir instituições",path:"/dashboard-master/administracao/instituicoes"}:!project?{title:"Criar N1 · Natação de homologação",text:"A N1 já é a instituição real. Agora crie apenas o projeto de Natação para a homologação Master.",label:"Criar projeto de homologação",path:"/dashboard-master/administracao/projetos?context=homologacao"}:professionals.length===0?{title:"Cadastrar técnico e profissionais",text:"Defina primeiro quem produzirá, validará e interpretará as evidências da N1 · Natação neste ciclo controlado.",label:"Cadastrar responsáveis",path:"/master/participantes?context=homologacao&role=profissional"}:!professionalAccessReady?{title:"Ativar acesso do técnico",text:"O técnico já está vinculado ao projeto, mas ainda precisa receber o convite e autenticar no AGP antes de a etapa 3 ser concluída.",label:"Ativar acesso técnico",path:"/master/homologacao/acesso-tecnico"}:athletes.length===0?{title:"Cadastrar atleta de homologação",text:"Depois dos responsáveis com acesso ativo, inclua um atleta controlado para percorrer o ciclo inteiro.",label:"Cadastrar atleta",path:"/master/participantes?context=homologacao&role=atleta"}:{title:complete?"Ciclo integral alcançado":"Continuar ciclo operacional",text:complete?"O ciclo chegou à resposta à intervenção.":"Siga a próxima responsabilidade dentro do ciclo real.",label:"Abrir ciclo guiado",path:`/master/homologacao/${institution.slug}`};
 return <main className="dashboard-master"><div className="dashboard-overlay master-page"><header className="dashboard-header master-header"><div><span className="master-eyebrow">Homologação Master</span><h1>N1 Academia · Natação</h1><p>A instituição N1 é preservada. Apenas os dados operacionais desta homologação serão controlados.</p></div><button className="master-button secondary" onClick={()=>navigate("/dashboard-master")}>Voltar</button></header>{error&&<div className="master-error">{error}</div>}<section className="master-now-card"><span className="master-eyebrow">Próxima ação</span><h2>{loading?"Lendo estado real...":next.title}</h2><p>{loading?"Verificando o que já existe.":next.text}</p><button className="master-button master-primary-action" disabled={loading} onClick={()=>navigate(next.path)}>{loading?"Aguarde":next.label}</button></section><section className="master-panel"><div className="master-section-heading"><div><span className="master-eyebrow">Roteiro obrigatório</span><h2>Todas as etapas</h2></div><strong>{progress.filter(Boolean).length}/{STEPS.length}</strong></div><ol className="master-activity-list">{STEPS.map((s,i)=><li key={s}><div><strong>{String(i+1).padStart(2,"0")}</strong><span>{s}</span></div><b>{progress[i]?"Concluída":"Pendente"}</b></li>)}</ol></section></div></main>;
}
