import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../supabaseClient";
import "../styles/dashboard-master.css";

const SLUG="agp-homologacao-master";
const STEPS=["Master e governança","Instituição","Técnico e profissionais","Atleta","Coleta de evidência","Validação profissional","Histórico longitudinal","Cruzamento analítico","Intervenção","Resposta à intervenção","Retorno ao histórico","Homologação integral"];
export default function MasterHomologationAuto(){
 const navigate=useNavigate(); const [ready,setReady]=useState(false),[working,setWorking]=useState(true),[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{let {data:inst,error:e}=await supabase.from("agp_instituicoes").select("id").eq("slug",SLUG).maybeSingle();if(e)throw e;if(!inst){const r=await supabase.from("agp_instituicoes").insert({nome:"AGP Homologação Controlada",slug:SLUG,tipo:"homologacao",localidade:"Ambiente interno",status:"ativo"}).select("id").single();if(r.error)throw r.error;inst=r.data;}const p=await supabase.from("agp_projetos_validacao").select("id").eq("instituicao_id",inst.id).maybeSingle();if(p.error)throw p.error;if(!p.data){const c=await supabase.from("agp_projetos_validacao").insert({instituicao_id:inst.id,nome:"Homologação integral multiusuário",objetivo:"Validar o ciclo completo antes do piloto real de 30 dias.",metodologia:"Base sintética controlada.",diretrizes:"Dados sintéticos não representam evidência científica real.",localidade:"Ambiente interno",status:"homologacao",versao_motor:"agp-core-v2"});if(c.error)throw c.error;}setReady(true);}catch(x){setError(x.message);}finally{setWorking(false);}})();},[]);
 return <main className="dashboard-master"><div className="dashboard-overlay master-page"><header className="dashboard-header master-header"><div><span className="master-eyebrow">Homologação controlada</span><h1>Validar o AGP inteiro antes do piloto real</h1><p>O ambiente é preparado automaticamente pela sessão Master.</p></div><div className="master-header-actions"><button className="master-button secondary" onClick={()=>navigate("/dashboard-master")}>Voltar</button><button className="master-button" disabled={working||!ready} onClick={()=>navigate(`/master/homologacao/${SLUG}`)}>{working?"Preparando...":"Abrir homologação"}</button></div></header>{error&&<div className="master-error">{error}</div>}<section className="master-panel"><div className="master-section-heading"><div><span className="master-eyebrow">Ciclo obrigatório</span><h2>Jornadas que precisam fechar</h2></div><strong>{STEPS.length}</strong></div><ol className="master-activity-list">{STEPS.map((s,i)=><li key={s}><div><strong>{String(i+1).padStart(2,"0")}</strong><span>{s}</span></div><b>Homologar</b></li>)}</ol></section><section className="master-panel"><span className="master-eyebrow">Depois</span><h2>Piloto real de 30 dias</h2><p>Somente após homologação integral e limpeza controlada da base sintética.</p></section></div></main>;
}
