import { useEffect,useMemo,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { createAthleteTrainingSession,getAthleteIndividualIntelligence } from "../services/athleteIntelligence";
import "../styles/dashboard-master.css";
import "../styles/athlete-daily-operation.css";
function localDateTimeValue(){const now=new Date(),offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,16)}
const INITIAL={data_hora_inicio:localDateTimeValue(),duracao_min:"",volume_planejado:"",volume_executado:"",intensidade_planejada:"",intensidade_percebida:"",carga_externa:"",foco:"",contexto:"",intercorrencias:""};
const numberOrNull=value=>value===""?null:Number(value);
export default function MasterAthleteDailyOperation(){
 const navigate=useNavigate(),{participantId}=useParams();
 const [intelligence,setIntelligence]=useState(null),[form,setForm]=useState(INITIAL),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){setLoading(true);setError("");try{setIntelligence(await getAthleteIndividualIntelligence(participantId));}catch(x){setError(`Falha ao carregar operação diária: ${x.message}`)}finally{setLoading(false)}}
 useEffect(()=>{load()},[participantId]);
 const readiness=intelligence?.prontidao_individual||intelligence?.prontidao||{},sessions=intelligence?.sessoes_recentes||[],person=intelligence?.pessoa||{},participant=intelligence?.participante||{},practical=intelligence?.devolucao_pratica||intelligence?.devolucao||{};
 const internalLoad=useMemo(()=>{const d=Number(form.duracao_min),i=Number(form.intensidade_percebida);if(!d||Number.isNaN(i))return null;return Math.round(d*i*10)/10},[form.duracao_min,form.intensidade_percebida]);
 const update=(field,value)=>setForm(c=>({...c,[field]:value}));
 const openReadiness=()=>navigate(`/master/coletas?${new URLSearchParams({projeto:participant.projeto_id||"",participante:participantId}).toString()}`);
 async function submit(event){event.preventDefault();setError("");setMessage("");if(!form.duracao_min)return setError("Informe a duração da sessão.");setSaving(true);try{const created=await createAthleteTrainingSession(participantId,{data_hora_inicio:new Date(form.data_hora_inicio).toISOString(),duracao_min:Number(form.duracao_min),volume_planejado:numberOrNull(form.volume_planejado),volume_executado:numberOrNull(form.volume_executado),intensidade_planejada:numberOrNull(form.intensidade_planejada),intensidade_percebida:numberOrNull(form.intensidade_percebida),carga_externa:numberOrNull(form.carga_externa),conteudo:{foco:form.foco.trim()||null,contexto:form.contexto.trim()||null},intercorrencias:form.intercorrencias.trim()||null});setMessage(`Sessão registrada. Carga interna: ${created.carga_interna??"não calculada"}.`);setForm({...INITIAL,data_hora_inicio:localDateTimeValue()});await load();}catch(x){setError(`Falha ao registrar sessão: ${x.message}`)}finally{setSaving(false)}}
 if(loading)return <main className="dashboard-master"><div className="dashboard-loading">Consolidando o dia do atleta...</div></main>;
 const hasReadiness=Boolean(readiness.ultimo||readiness.amostras>0);
 return <main className="dashboard-master"><div className="dashboard-overlay master-page daily-operation-page">
  <header className="dashboard-header master-header"><div><span className="master-eyebrow">Hoje</span><h1>{person.nome||"Atleta"}</h1><p>O AGP apresenta somente a próxima ação necessária para fechar o dia.</p></div><button className="master-button secondary" onClick={()=>navigate(`/master/atletas/${participantId}`)}>Voltar ao atleta</button></header>
  {message&&<div className="master-feedback success">{message}</div>}{error&&<div className="master-error" role="alert">{error}</div>}
  {!hasReadiness?<section className="decision-hero"><div><span className="master-eyebrow">Próxima ação</span><h2>Registrar a prontidão do dia</h2><p>Sem evidência de prontidão, o AGP não interpreta o estado atual nem antecipa decisão.</p><button className="master-button" onClick={openReadiness}>Registrar prontidão</button></div></section>:
  <><section className="daily-guidance"><div><span className="master-eyebrow">Situação atual</span><h2>{practical.estado?practical.estado.replaceAll("_"," "):"Prontidão registrada"}</h2><p>{practical.mensagem||"A evidência do dia já está disponível. Registre a sessão quando ela ocorrer."}</p></div><strong>{practical.acao_prioritaria||"Registrar sessão do dia"}</strong></section>
  <form className="master-panel daily-session-form" onSubmit={submit}><span className="master-eyebrow">Próxima ação</span><h2>Registrar sessão</h2><div className="daily-form-grid"><label>Início<input type="datetime-local" value={form.data_hora_inicio} onChange={e=>update("data_hora_inicio",e.target.value)} required/></label><label>Duração (min)<input type="number" min="1" max="600" value={form.duracao_min} onChange={e=>update("duracao_min",e.target.value)} required/></label><label>RPE (0–10)<input type="number" min="0" max="10" step="0.1" value={form.intensidade_percebida} onChange={e=>update("intensidade_percebida",e.target.value)}/></label><label>Carga interna<input value={internalLoad??"Calculada com duração × RPE"} readOnly/></label></div><details><summary>Adicionar contexto e detalhes da sessão</summary><div className="daily-form-grid"><label>Intensidade planejada<input type="number" min="0" max="10" step="0.1" value={form.intensidade_planejada} onChange={e=>update("intensidade_planejada",e.target.value)}/></label><label>Volume planejado<input type="number" step="0.1" value={form.volume_planejado} onChange={e=>update("volume_planejado",e.target.value)}/></label><label>Volume executado<input type="number" step="0.1" value={form.volume_executado} onChange={e=>update("volume_executado",e.target.value)}/></label><label>Carga externa<input type="number" step="0.1" value={form.carga_externa} onChange={e=>update("carga_externa",e.target.value)}/></label></div><label>Foco da sessão<input value={form.foco} onChange={e=>update("foco",e.target.value)}/></label><label>Contexto<textarea rows="3" value={form.contexto} onChange={e=>update("contexto",e.target.value)}/></label><label>Intercorrências<textarea rows="3" value={form.intercorrencias} onChange={e=>update("intercorrencias",e.target.value)}/></label></details><button className="master-button" disabled={saving}>{saving?"Registrando...":"Registrar sessão"}</button></form></>}
  <details className="master-panel"><summary>Ver histórico recente</summary>{sessions.length===0?<div className="master-empty">Nenhuma sessão registrada.</div>:<ul className="master-activity-list">{sessions.map(s=><li key={s.id}><div><strong>{new Date(s.data_hora_inicio).toLocaleString("pt-BR")}</strong><span>{s.duracao_min||"—"} min · RPE {s.intensidade_percebida??"—"} · carga {s.carga_interna??"—"}</span></div></li>)}</ul>}</details>
 </div></main>;
}